### PR TITLE
fix: jupyter installation

### PR DESCRIPTION
**Pull request by bddppq**

### CODE REVIEW

**Review by bobmayuze — APPROVED** [review]
LGTM

**Comment by bddppq** [comment]
test: https://github.com/leptonai/leptonai/actions/runs/9474396257

**Comment by bddppq** [comment]
test: https://github.com/leptonai/leptonai/actions/runs/9474460235

**Comment by bddppq** [comment]
test: https://github.com/leptonai/leptonai/actions/runs/9474592860

**Comment by bddppq** [comment]
test: https://github.com/leptonai/leptonai/actions/runs/9474648949

**Comment by bddppq** [comment]
test: https://github.com/leptonai/leptonai/actions/runs/9474719461

**Comment by bddppq** [comment]
test: https://github.com/leptonai/leptonai/actions/runs/9474825503

**Comment by bddppq** [comment]
test: https://github.com/leptonai/leptonai/actions/runs/9474969405

**Comment by bddppq** [comment]
test: https://github.com/leptonai/leptonai/actions/runs/9475943933

**Pull request merged**
