### PR TITLE
release: 0.17.0

### PR DESCRIPTION
**Pull request by bddppq**
Update torch version to latest 2.2.0

### CODE REVIEW

**Comment by bddppq** [comment]
https://github.com/leptonai/leptonai/actions/runs/7717919018

**Comment by bddppq** [comment]
https://github.com/leptonai/leptonai/actions/runs/7718153994

**Comment by bddppq** [comment]
https://github.com/leptonai/leptonai/actions/runs/7718227889

**Review by Yangqing — APPROVED** [review]

**Review by kcordoc — COMMENTED** [review]
ALLOW_ORIGINS_URLS = [
    LEPTON_HOMEPAGE_URL,
    LEPTON_HOMEPAGE_WWW_URL,
    LEPTON_DASHBOARD_URL,
    LEPTON_DASHBOARD_DAILY_URL,
]

This causes CORS issue when frontend is deployed outside LEPTON

**Pull request merged**
