### PR TITLE
feat(cli): warn the user that the workspace needs to be created before usage.

### LINKED ISSUE #402: [BUG] cannot find workspace
**Describe the bug**

lep login
lep workspace login 

fails with following error 
RuntimeError: Cannot find the workspace with id /api/v1.

**To Reproduce**
lep login fnog4fwd:[redacted]
lep workspace login -i fnog4fwd -t [redacted]

**Expected behavior**
command execute successfully

**Environment (please complete the following information):**
 - OS: MacOs 14.4 (23E214)
 - Python version: 3.9.6
 - LeptonAI library version: lep, version 0.20.4

**Additional context**

### PR DESCRIPTION
**Pull request by Yangqing**
This is to coordinate with the fronend lazy-creation policy. Added test by having a dummy workspace set up and tested via github secrets.

Closes #402

### CODE REVIEW

**Comment by Yangqing** [comment]
Example output:
```
(lepton) ➜  sdk git:(yqwsstart) ✗ lep login -c $TESTONLY_NO_MOTHERSHIP_LOGIN_CREDENTIALS========================================================
    _     _____ ____ _____ ___  _   _       _    ___     
   | |   | ____|  _ \_   _/ _ \| \ | |     / \  |_ _|    
   | |   |  _| | |_) || || | | |  \| |    / _ \  | |     
   | |___| |___|  __/ | || |_| | |\  |   / ___ \ | |     
   |_____|_____|_|    |_| \___/|_| \_|  /_/   \_\___|    

========================================================
Workspace emt2tod3 is registerd, but not set up yet. To set it up, Please visit
  https://dashboard.lepton.ai/workspace/emt2tod3/setup
 After that, you can log in here and use the workspace via CLI or API.
```

**Comment by vthinkxie** [comment]
the ascii could be https://github.com/leptonai/lepton/pull/8720/files#diff-6e7cb231844130719980a7504c652e6842a50013b632a072df525c81dd375b13R19

lol

**Comment by Yangqing** [comment]
Dine :)

**Review by vthinkxie — APPROVED** [review]
lgtm

**Pull request merged**
