### PR TITLE
Adds einops dependency in hf text generation Photon

### PR DESCRIPTION
**Pull request by mani-kantap**
**Title:** Add 'einops' dependency for 'microsoft/phi-1_5' model support in Huggingface Photon

**Description:**
This PR addresses the need for an additional dependency, 'einops,' to enable support for the 'microsoft/phi-1_5' model in Huggingface Photon's text generation capabilities.

**Changes Made:**
In the leptonai/photon/hf/hf.py file, I've modified the HuggingfaceTextGenerationPhoton class by adding the 'einops' dependency to the requirement_dependency list.

### CODE REVIEW

**Comment by Yangqing** [comment]
Thanks! Would you mind sharing what command you used that triggered a dependency error? Strictly speaking, the microsoft/phi-1.5 dependency was explicitly specified here:

https://github.com/leptonai/leptonai/blob/main/leptonai/photon/hf/hf_dependencies.py#L22

So I am wondering whether our mechanism failed. Will definitely take a look :)

**Comment by mani-kantap** [comment]
I encountered a dependency error when running the Photon created with the commands:

Creation of Photon:
`!lep photon create -n phi2 -m hf:microsoft/phi-1_5`


Running the Photon:
`!lep photon run -n phi2 --local`

Let me know if this is not the way to run a Photon, I'm not sure😇.

**Comment by Yangqing** [comment]
Ah thanks! Yes, in this case, we recommend you to install local dependencies yourself - the reason is that we don't want to implicitly install local dependencies. The script will give you a recommendation - in this case, doing `pip install einops` would add the specific dependency. This is also reflected in the fail message which I paste for your convenience:

```
Failed to launch photon: HuggingFace reported missing packages for the specified pipeline. You can 
see the hf error message above. 

This is not a bug of LeptonAI, as HuggingFace pipelines do not have a standard way to pre-determine 
and install dependencies yet. As a best-effort attempt, here are steps you can take to fix this 
issue:

1. If you are running locally, you can install the missing packages with pip as follows:

pip install einops

(note that some package names and pip names may be different, and you may need to search pypi for 
the correct package name)

2. If you are using LeptonAI library, we maintain a mapping from known HuggingFace pipelines to 
their dependencies. We appreciate if you can send a PR to https://github.com/leptonai/leptonai/ to 
add the missing dependencies.Specifically, it looks like this:

"text-generation":[
    "einops"
]
```

**Comment by mani-kantap** [comment]
I understand now, but based on this [link](https://github.com/leptonai/leptonai/blob/main/leptonai/photon/hf/hf_dependencies.py#L22), it seems like it should work without requiring manual installation, although I may not have a full understanding of the entire process.

> Thanks! Would you mind sharing what command you used that triggered a dependency error? Strictly speaking, the microsoft/phi-1.5 dependency was explicitly specified here:
> 
> https://github.com/leptonai/leptonai/blob/main/leptonai/photon/hf/hf_dependencies.py#L22
> 
> So I am wondering whether our mechanism failed. Will definitely take a look :)

**Pull request closed without merging**
